name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run tests and Linters
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install

      - name: Linter
        run: pnpm lint:check

      - name: Formatter
        run: pnpm format:check

      - name: Type checking
        run: pnpm type:check
